# this file contains the services that must always run to support the solution in any case
services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - "3306"
    ports: 
      - "0.0.0.0:3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    secrets:
      - db_name
      - db_username
      - db_password
      - db_root_password
    networks:
      - shared-network

  clamav:
    image: clamav/clamav:1.0.5
    restart: on-failure:3
    expose:
      - "3310"
    ports: 
      - "0.0.0.0:3310:3310"
    environment: 
      - "CLAMD_CONF_FILE=/mnt/clamd.conf"
    volumes:
      - clamav_volume:/var/lib/clamav
      - ../_config/clamd.conf:/mnt/clamd.conf
    networks:
      - shared-network
  
  fe_internal:
    image: agora-fe_internal:latest
    ports:
      - "0.0.0.0:4000:4000"
    env_file:
      - .env.fe-internal
    environment:
      - THEME=${THEME}
    networks:
      - shared-network
  
  fe_public:
    image: agora-fe_public:latest
    env_file: 
      - .env.fe-public
    environment:
      - THEME=${THEME}
    networks:
      - shared-network

  fe_public_nginx:
    image: agora-fe_public_nginx:latest
    ports: 
      - "0.0.0.0:4001:4001"
    env_file:
      - .env.fe-public-nginx
    networks:
      - shared-network

networks:
  shared-network:
    name: agora-shared-network
      
secrets:
  db_name:
    file: ../_config/secrets/db_name
  db_username:
    file: ../_config/secrets/db_username
  db_password:
    file: ../_config/secrets/db_password
  db_root_password:
    file: ../_config/secrets/db_root_password

volumes:
  db_volume:
    name: OS2agora-db_volume
  clamav_volume:
    name: OS2agora-clamav_volume
