services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - "3306"
    ports: 
      - "0.0.0.0:3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    secrets:
      - db_name
      - db_username
      - db_password
      - db_root_password
    networks:
      - shared-network

  clamav:
    image: clamav/clamav:1.0.5
    restart: on-failure:3
    expose:
      - "3310"
    ports: 
      - "0.0.0.0:3310:3310"
    environment: 
      - "CLAMD_CONF_FILE=/mnt/clamd.conf"
    volumes:
      - clamav_volume:/var/lib/clamav
      - ../_config/clamd.conf:/mnt/clamd.conf
    networks:
      - shared-network

  api:
    image: agora-api:latest
    restart: always
    expose:
      - "5000"
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - db
      - clamav
    env_file: 
      - ./.env.api
    environment:
      - RUNNING_IN_DOCKER=yes
      - FileDrives__HearingFileDriveBasePath=/var/file-drive
      - FileDrives__ExportFileDriveBasePath=/var/exports
    secrets:
      - ConnectionStrings__DefaultConnection
      - JwtSettings__Secret
      - OAuth2__InternalClientId
      - OAuth2__PublicClientId
      - OAuth2__InternalClientSecret
      - OAuth2__PublicClientSecret
      - EBoks__ClientId
      - EBoks__ClientSecret
      - Email__Password 
      - Email__UserName
    volumes:
      - api_encryption-keys:/root/.aspnet/DataProtection-Keys
      - api_file-drive:/var/file-drive
      - api_exports:/var/exports
    networks:
      - shared-network

networks:
  shared-network:
    name: agora-shared-network
      
secrets:
  db_name:
    file: ../_config/secrets/db_name
  db_username:
    file: ../_config/secrets/db_username
  db_password:
    file: ../_config/secrets/db_password
  db_root_password:
    file: ../_config/secrets/db_root_password
  ConnectionStrings__DefaultConnection:
    file: ../_config/secrets/ConnectionStrings__DefaultConnection
  JwtSettings__Secret:
    file: ../_config/secrets/JwtSettings__Secret
  OAuth2__InternalClientId:
    file: ../_config/secrets/OAuth2__InternalClientId
  OAuth2__PublicClientId:
    file: ../_config/secrets/OAuth2__PublicClientId
  OAuth2__InternalClientSecret:
    file: ../_config/secrets/OAuth2__InternalClientSecret
  OAuth2__PublicClientSecret:
    file: ../_config/secrets/OAuth2__PublicClientSecret
  EBoks__ClientId:
    file: ../_config/secrets/EBoks__ClientId
  EBoks__ClientSecret:
    file: ../_config/secrets/EBoks__ClientSecret
  Email__Password:
    file: ../_config/secrets/Email__Password
  Email__UserName:
    file: ../_config/secrets/Email__UserName

volumes:
  db_volume:
    name: OS2agora-db_volume
  clamav_volume:
    name: OS2agora-clamav_volume
  api_encryption-keys:
    name: OS2agora-api_encryption-keys
  api_file-drive:
    name: OS2agora-api_file-drive
  api_exports:
    name: OS2agora-api_exports
