# this file contains the services that must always run to support the solution in any case
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - "3306"
    volumes:
      - db_volume:/var/lib/mysql
    secrets:
      - db_name
      - db_username
      - db_password
      - db_root_password
    networks:
      - shared-network

  clamav:
    image: clamav/clamav:1.0.5
    restart: always
    expose:
      - "3310"
    environment: 
      - "CLAMD_CONF_FILE=/mnt/clamd.conf"
    volumes:
      - clamav_volume:/var/lib/clamav
      - ../_config/clamd.conf:/mnt/clamd.conf
    networks:
      - shared-network

  proxy:
    image: agora-proxy:latest
    build:
      context: ../_images/proxy
    restart: always
    ports:
      - "0.0.0.0:8080:444"
      - "0.0.0.0:8081:445"
    env_file: 
      - ./.env.proxy
    environment:
      OUT_API_HOST: "api"
      OUT_API_PORT: "5000"
      OUT_PUBLIC_FE_HOST: "fe_public_nginx"
      OUT_PUBLIC_FE_PORT: "4001"
      OUT_INTERNAL_FE_HOST: "fe_internal"
      OUT_INTERNAL_FE_PORT: "4000"
    networks:
      - incoming
      - shared-network

  api:
    image: agora-api:latest
    restart: always
    expose:
      - "5000"
    depends_on:
      - db
      - clamav
    env_file: 
      - ./.env.api
    environment:
      - RUNNING_IN_DOCKER=yes
      - FileDrives__HearingFileDriveBasePath=/var/file-drive
      - FileDrives__ExportFileDriveBasePath=/var/exports
    secrets:
      - ConnectionStrings__DefaultConnection
      - JwtSettings__Secret
      - OAuth2__InternalClientId
      - OAuth2__PublicClientId
      - OAuth2__InternalClientSecret
      - OAuth2__PublicClientSecret
      - EBoks__ClientId
      - EBoks__ClientSecret
      - Email__Password 
      - Email__UserName
    volumes:
      - api_encryption-keys:/root/.aspnet/DataProtection-Keys
      - api_file-drive:/var/file-drive
      - api_exports:/var/exports
    networks:
      - shared-network
  
  fe_internal:
    image: agora-fe_internal:latest
    restart: always
    expose:
      - "4000"
    env_file:
      - .env.fe-internal
    environment:
      - THEME=${THEME}
    networks:
      - shared-network
  
  fe_public:
    image: agora-fe_public:latest
    restart: always
    env_file: 
      - .env.fe-public
    environment:
      - THEME=${THEME}
    networks:
      - shared-network

  fe_public_nginx:
    image: agora-fe_public_nginx:latest
    restart: always
    expose:
      - "4001"
    env_file:
      - .env.fe-public-nginx
    networks:
      - shared-network

networks:
  shared-network:
    name: agora-shared-network
  incoming:
    name: agora-proxy-frontend
      
secrets:
  db_name:
    file: ../_config/secrets/db_name
  db_username:
    file: ../_config/secrets/db_username
  db_password:
    file: ../_config/secrets/db_password
  db_root_password:
    file: ../_config/secrets/db_root_password
  ConnectionStrings__DefaultConnection:
    file: ../_config/secrets/ConnectionStrings__DefaultConnection
  JwtSettings__Secret:
    file: ../_config/secrets/JwtSettings__Secret
  OAuth2__InternalClientId:
    file: ../_config/secrets/OAuth2__InternalClientId
  OAuth2__PublicClientId:
    file: ../_config/secrets/OAuth2__PublicClientId
  OAuth2__InternalClientSecret:
    file: ../_config/secrets/OAuth2__InternalClientSecret
  OAuth2__PublicClientSecret:
    file: ../_config/secrets/OAuth2__PublicClientSecret
  EBoks__ClientId:
    file: ../_config/secrets/EBoks__ClientId
  EBoks__ClientSecret:
    file: ../_config/secrets/EBoks__ClientSecret
  Email__Password:
    file: ../_config/secrets/Email__Password
  Email__UserName:
    file: ../_config/secrets/Email__UserName

volumes:
  db_volume:
    name: OS2agora-db_volume
  clamav_volume:
    name: OS2agora-clamav_volume
  api_encryption-keys:
    name: OS2agora-api_encryption-keys
  api_file-drive:
    name: OS2agora-api_file-drive
  api_exports:
    name: OS2agora-api_exports
